/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewResponseListResultCustomModel } from '../../models/review-response-list-result-custom-model';

export interface ApiReviewBookBookIdGet$Plain$Params {
  bookId: number;
}

export function apiReviewBookBookIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiReviewBookBookIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ReviewResponseListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiReviewBookBookIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('bookId', params.bookId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReviewResponseListResultCustomModel>;
    })
  );
}

apiReviewBookBookIdGet$Plain.PATH = '/api/Review/book/{bookId}';
