/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardStatsResponse } from '../../models/dashboard-stats-response';

export interface ApiDashboardStatsGet$Plain$Params {
}

export function apiDashboardStatsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiDashboardStatsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardStatsResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDashboardStatsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardStatsResponse>;
    })
  );
}

apiDashboardStatsGet$Plain.PATH = '/api/Dashboard/stats';
