/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookBestSellerResponseListResultCustomModel } from '../../models/book-best-seller-response-list-result-custom-model';

export interface ApiDashboardBestSellersGet$Plain$Params {
}

export function apiDashboardBestSellersGet$Plain(http: HttpClient, rootUrl: string, params?: ApiDashboardBestSellersGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BookBestSellerResponseListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiDashboardBestSellersGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookBestSellerResponseListResultCustomModel>;
    })
  );
}

apiDashboardBestSellersGet$Plain.PATH = '/api/Dashboard/best-sellers';
