/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectResultCustomModel } from '../../models/object-result-custom-model';

export interface ApiFavoriteUserBookDelete$Plain$Params {
  userId?: number;
  bookId?: number;
}

export function apiFavoriteUserBookDelete$Plain(http: HttpClient, rootUrl: string, params?: ApiFavoriteUserBookDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiFavoriteUserBookDelete$Plain.PATH, 'delete');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.query('bookId', params.bookId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectResultCustomModel>;
    })
  );
}

apiFavoriteUserBookDelete$Plain.PATH = '/api/Favorite/user-book';
