/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectResultCustomModel } from '../../models/object-result-custom-model';

export interface ApiFavoriteDeleteIdDelete$Json$Params {
  id: number;
}

export function apiFavoriteDeleteIdDelete$Json(http: HttpClient, rootUrl: string, params: ApiFavoriteDeleteIdDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiFavoriteDeleteIdDelete$Json.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectResultCustomModel>;
    })
  );
}

apiFavoriteDeleteIdDelete$Json.PATH = '/api/Favorite/Delete/{id}';
