/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiFavoriteDeleteByUserBookDelete$Params {
  userId?: number;
  bookId?: number;
}

export function apiFavoriteDeleteByUserBookDelete(http: HttpClient, rootUrl: string, params?: ApiFavoriteDeleteByUserBookDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiFavoriteDeleteByUserBookDelete.PATH, 'delete');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.query('bookId', params.bookId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiFavoriteDeleteByUserBookDelete.PATH = '/api/Favorite/DeleteByUserBook';
