/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectResultCustomModel } from '../../models/object-result-custom-model';

export interface ApiBookCreatePost$Plain$Params {
      body?: {
'Title'?: string;
'Author'?: string;
'GenreId'?: number;
'Price'?: number;
'Stock'?: number;
'Description'?: string;
'PublishedDate'?: string;
'CoverImage'?: Blob;
}
}

export function apiBookCreatePost$Plain(http: HttpClient, rootUrl: string, params?: ApiBookCreatePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiBookCreatePost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectResultCustomModel>;
    })
  );
}

apiBookCreatePost$Plain.PATH = '/api/Book/Create';
