/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ObjectResultCustomModel } from '../../models/object-result-custom-model';

export interface ApiBookIdPut$Json$Params {
  id: number;
      body?: {
'Title'?: string;
'Author'?: string;
'GenreId'?: number;
'Price'?: number;
'Stock'?: number;
'Description'?: string;
'PublishedDate'?: string;
'CoverImage'?: Blob;
}
}

export function apiBookIdPut$Json(http: HttpClient, rootUrl: string, params: ApiBookIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiBookIdPut$Json.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectResultCustomModel>;
    })
  );
}

apiBookIdPut$Json.PATH = '/api/Book/{id}';
