/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ComboResponseResultCustomModel } from '../../models/combo-response-result-custom-model';

export interface ApiComboIdGet$Json$Params {
  id: number;
}

export function apiComboIdGet$Json(http: HttpClient, rootUrl: string, params: ApiComboIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ComboResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiComboIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ComboResponseResultCustomModel>;
    })
  );
}

apiComboIdGet$Json.PATH = '/api/Combo/{id}';
