/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ShippingAddressResponseListResultCustomModel } from '../../models/shipping-address-response-list-result-custom-model';

export interface ApiShippingAddressUserUserIdGet$Plain$Params {
  userId: number;
}

export function apiShippingAddressUserUserIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiShippingAddressUserUserIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ShippingAddressResponseListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiShippingAddressUserUserIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ShippingAddressResponseListResultCustomModel>;
    })
  );
}

apiShippingAddressUserUserIdGet$Plain.PATH = '/api/ShippingAddress/user/{userId}';
