/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenreRequest } from '../../models/genre-request';
import { ObjectResultCustomModel } from '../../models/object-result-custom-model';

export interface ApiGenreUpdateIdPut$Json$Params {
  id: number;
      body?: GenreRequest
}

export function apiGenreUpdateIdPut$Json(http: HttpClient, rootUrl: string, params: ApiGenreUpdateIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiGenreUpdateIdPut$Json.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ObjectResultCustomModel>;
    })
  );
}

apiGenreUpdateIdPut$Json.PATH = '/api/Genre/Update/{id}';
