/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenreResponseListResultCustomModel } from '../../models/genre-response-list-result-custom-model';

export interface ApiGenreSearchGet$Json$Params {
  keyword?: string;
}

export function apiGenreSearchGet$Json(http: HttpClient, rootUrl: string, params?: ApiGenreSearchGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GenreResponseListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiGenreSearchGet$Json.PATH, 'get');
  if (params) {
    rb.query('keyword', params.keyword, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenreResponseListResultCustomModel>;
    })
  );
}

apiGenreSearchGet$Json.PATH = '/api/Genre/search';
