/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenreResponseResultCustomModel } from '../../models/genre-response-result-custom-model';

export interface ApiGenreIdGet$Json$Params {
  id: number;
}

export function apiGenreIdGet$Json(http: HttpClient, rootUrl: string, params: ApiGenreIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GenreResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiGenreIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenreResponseResultCustomModel>;
    })
  );
}

apiGenreIdGet$Json.PATH = '/api/Genre/{id}';
