/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BookResponse } from './models/book-response';
export type { BookResponseListResultCustomModel } from './models/book-response-list-result-custom-model';
export type { BookResponseResultCustomModel } from './models/book-response-result-custom-model';
export type { ChangePasswordRequest } from './models/change-password-request';
export type { ComboResponse } from './models/combo-response';
export type { ComboResponseListResultCustomModel } from './models/combo-response-list-result-custom-model';
export type { ComboResponseResultCustomModel } from './models/combo-response-result-custom-model';
export type { DashboardStatsResponse } from './models/dashboard-stats-response';
export type { FavoriteRequest } from './models/favorite-request';
export type { FavoriteResponse } from './models/favorite-response';
export type { FavoriteResponseListResultCustomModel } from './models/favorite-response-list-result-custom-model';
export type { ForgotPasswordRequest } from './models/forgot-password-request';
export type { GenreRequest } from './models/genre-request';
export type { GenreResponse } from './models/genre-response';
export type { GenreResponseListResultCustomModel } from './models/genre-response-list-result-custom-model';
export type { GenreResponseResultCustomModel } from './models/genre-response-result-custom-model';
export type { GoogleLoginRequest } from './models/google-login-request';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { ObjectResultCustomModel } from './models/object-result-custom-model';
export type { OrderItemRequest } from './models/order-item-request';
export type { OrderItemResponse } from './models/order-item-response';
export type { OrderRequest } from './models/order-request';
export type { OrderResponse } from './models/order-response';
export type { OrderResponseListResultCustomModel } from './models/order-response-list-result-custom-model';
export type { OrderResponseResultCustomModel } from './models/order-response-result-custom-model';
export type { RegisterRequest } from './models/register-request';
export type { ResetPasswordRequest } from './models/reset-password-request';
export type { ReviewRequest } from './models/review-request';
export type { ReviewResponse } from './models/review-response';
export type { ReviewResponseListResultCustomModel } from './models/review-response-list-result-custom-model';
export type { ShippingAddressRequest } from './models/shipping-address-request';
export type { ShippingAddressResponse } from './models/shipping-address-response';
export type { ShippingAddressResponseListResultCustomModel } from './models/shipping-address-response-list-result-custom-model';
export type { StringResultCustomModel } from './models/string-result-custom-model';
export type { UserRequest } from './models/user-request';
export type { UserResponse } from './models/user-response';
export type { UserResponseListResultCustomModel } from './models/user-response-list-result-custom-model';
export type { UserResponseResultCustomModel } from './models/user-response-result-custom-model';
export type { UserUpdateRequest } from './models/user-update-request';
export type { VoucherRequest } from './models/voucher-request';
export type { VoucherResponse } from './models/voucher-response';
export type { VoucherResponseListResultCustomModel } from './models/voucher-response-list-result-custom-model';
export type { WeatherForecast } from './models/weather-forecast';
