/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { FavoriteRequest } from './models/favorite-request';
export type { GenreRequest } from './models/genre-request';
export type { OrderItemRequest } from './models/order-item-request';
export type { OrderRequest } from './models/order-request';
export type { ReviewRequest } from './models/review-request';
export type { ShippingAddressRequest } from './models/shipping-address-request';
export type { UserRequest } from './models/user-request';
export type { WeatherForecast } from './models/weather-forecast';
