/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookBestSellerResponse {
  author?: string | null;
  bookId?: number;
  coverImageUrl?: string | null;
  title?: string | null;
  totalSold?: number;
}
