/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookResponse {
  author?: string | null;
  averageRating?: number | null;
  bookId?: number;
  coverImageUrl?: string | null;
  description?: string | null;
  genreId?: number | null;
  price?: number;
  publishedDate?: string | null;
  stock?: number;
  title?: string | null;
}
