/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactFormDto {
  email?: string | null;
  message?: string | null;
  name?: string | null;
  phone?: string | null;
  subject?: string | null;
}
