/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardStatsResponse {
  totalBooks?: number;
  totalCombos?: number;
  totalOrders?: number;
  totalSales?: number;
  totalUsers?: number;
}
