/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FavoriteResponse {
  addedDate?: string | null;
  bookId?: number;
  bookTitle?: string | null;
  coverImageUrl?: string | null;
  favoriteId?: number;
  userId?: number;
  username?: string | null;
}
