/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderItemResponse {
  bookId?: number;
  bookTitle?: string | null;
  orderItemId?: number;
  price?: number;
  quantity?: number;
}
