/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderItemRequest } from '../models/order-item-request';
export interface OrderRequest {
  items?: Array<OrderItemRequest> | null;
  shippingAddressId?: number;
  status?: string | null;
  userId?: number;
}
