/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderItemRequest } from '../models/order-item-request';
export interface OrderRequest {
  address?: string | null;
  isPaid?: boolean;
  items?: Array<OrderItemRequest> | null;
  paymentMethod?: string | null;
  phoneNumber?: string | null;
  recipientName?: string | null;
  shippingAddressId?: number | null;
  userId?: number | null;
  voucherCode?: string | null;
}
