/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderItemResponse } from '../models/order-item-response';
export interface OrderResponse {
  isPaid?: boolean | null;
  items?: Array<OrderItemResponse> | null;
  orderDate?: string | null;
  orderId?: number;
  paymentMethod?: string | null;
  shippingAddressId?: number;
  status?: string | null;
  totalAmount?: number | null;
  userId?: number;
  username?: string | null;
}
