/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderItemRequest {
  bookId?: number | null;
  comboId?: number | null;
  price?: number;
  quantity?: number;
}
