/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
  email?: string | null;
  password?: string | null;
  username?: string | null;
}
