/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResetPasswordRequest {
  email?: string | null;
  newPassword?: string | null;
  token?: string | null;
}
