/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewResponse {
  bookId?: number;
  bookTitle?: string | null;
  comment?: string | null;
  rating?: number;
  reviewDate?: string | null;
  reviewId?: number;
  userId?: number;
  username?: string | null;
}
