/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShippingAddressResponse {
  address?: string | null;
  addressId?: number;
  phoneNumber?: string | null;
  recipientName?: string | null;
  userId?: number;
  username?: string | null;
}
