/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ShippingAddressRequest {
  address?: string | null;
  phoneNumber?: string | null;
  recipientName?: string | null;
  userId?: number;
}
