/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  email?: string | null;
  role?: string | null;
  userId?: number;
  username?: string | null;
}
