/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VoucherRequest {
  code?: string | null;
  discountPercent?: number;
  expiryDate?: string;
  maxDiscount?: number;
  minOrderAmount?: number;
  usageLimit?: number;
}
