/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VoucherResponse {
  code?: string | null;
  discountPercent?: number | null;
  expiryDate?: string | null;
  maxDiscount?: number | null;
  minOrderAmount?: number | null;
  usageLimit?: number | null;
  usedCount?: number | null;
  voucherId?: number;
}
