/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiShippingAddressGet$Json } from '../fn/shipping-address/api-shipping-address-get-json';
import { ApiShippingAddressGet$Json$Params } from '../fn/shipping-address/api-shipping-address-get-json';
import { apiShippingAddressGet$Plain } from '../fn/shipping-address/api-shipping-address-get-plain';
import { ApiShippingAddressGet$Plain$Params } from '../fn/shipping-address/api-shipping-address-get-plain';
import { apiShippingAddressIdDelete$Json } from '../fn/shipping-address/api-shipping-address-id-delete-json';
import { ApiShippingAddressIdDelete$Json$Params } from '../fn/shipping-address/api-shipping-address-id-delete-json';
import { apiShippingAddressIdDelete$Plain } from '../fn/shipping-address/api-shipping-address-id-delete-plain';
import { ApiShippingAddressIdDelete$Plain$Params } from '../fn/shipping-address/api-shipping-address-id-delete-plain';
import { apiShippingAddressIdPut$Json } from '../fn/shipping-address/api-shipping-address-id-put-json';
import { ApiShippingAddressIdPut$Json$Params } from '../fn/shipping-address/api-shipping-address-id-put-json';
import { apiShippingAddressIdPut$Plain } from '../fn/shipping-address/api-shipping-address-id-put-plain';
import { ApiShippingAddressIdPut$Plain$Params } from '../fn/shipping-address/api-shipping-address-id-put-plain';
import { apiShippingAddressPost$Json } from '../fn/shipping-address/api-shipping-address-post-json';
import { ApiShippingAddressPost$Json$Params } from '../fn/shipping-address/api-shipping-address-post-json';
import { apiShippingAddressPost$Plain } from '../fn/shipping-address/api-shipping-address-post-plain';
import { ApiShippingAddressPost$Plain$Params } from '../fn/shipping-address/api-shipping-address-post-plain';
import { apiShippingAddressUserUserIdGet$Json } from '../fn/shipping-address/api-shipping-address-user-user-id-get-json';
import { ApiShippingAddressUserUserIdGet$Json$Params } from '../fn/shipping-address/api-shipping-address-user-user-id-get-json';
import { apiShippingAddressUserUserIdGet$Plain } from '../fn/shipping-address/api-shipping-address-user-user-id-get-plain';
import { ApiShippingAddressUserUserIdGet$Plain$Params } from '../fn/shipping-address/api-shipping-address-user-user-id-get-plain';
import { ObjectResultCustomModel } from '../models/object-result-custom-model';
import { ShippingAddressResponseListResultCustomModel } from '../models/shipping-address-response-list-result-custom-model';

@Injectable({ providedIn: 'root' })
export class ShippingAddressService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiShippingAddressGet()` */
  static readonly ApiShippingAddressGetPath = '/api/ShippingAddress';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressGet$Plain$Response(params?: ApiShippingAddressGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ShippingAddressResponseListResultCustomModel>> {
    return apiShippingAddressGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressGet$Plain(params?: ApiShippingAddressGet$Plain$Params, context?: HttpContext): Observable<ShippingAddressResponseListResultCustomModel> {
    return this.apiShippingAddressGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShippingAddressResponseListResultCustomModel>): ShippingAddressResponseListResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressGet$Json$Response(params?: ApiShippingAddressGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ShippingAddressResponseListResultCustomModel>> {
    return apiShippingAddressGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressGet$Json(params?: ApiShippingAddressGet$Json$Params, context?: HttpContext): Observable<ShippingAddressResponseListResultCustomModel> {
    return this.apiShippingAddressGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShippingAddressResponseListResultCustomModel>): ShippingAddressResponseListResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiShippingAddressPost()` */
  static readonly ApiShippingAddressPostPath = '/api/ShippingAddress';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiShippingAddressPost$Plain$Response(params?: ApiShippingAddressPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
    return apiShippingAddressPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiShippingAddressPost$Plain(params?: ApiShippingAddressPost$Plain$Params, context?: HttpContext): Observable<ObjectResultCustomModel> {
    return this.apiShippingAddressPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectResultCustomModel>): ObjectResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiShippingAddressPost$Json$Response(params?: ApiShippingAddressPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
    return apiShippingAddressPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiShippingAddressPost$Json(params?: ApiShippingAddressPost$Json$Params, context?: HttpContext): Observable<ObjectResultCustomModel> {
    return this.apiShippingAddressPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectResultCustomModel>): ObjectResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiShippingAddressUserUserIdGet()` */
  static readonly ApiShippingAddressUserUserIdGetPath = '/api/ShippingAddress/user/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressUserUserIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressUserUserIdGet$Plain$Response(params: ApiShippingAddressUserUserIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ShippingAddressResponseListResultCustomModel>> {
    return apiShippingAddressUserUserIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressUserUserIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressUserUserIdGet$Plain(params: ApiShippingAddressUserUserIdGet$Plain$Params, context?: HttpContext): Observable<ShippingAddressResponseListResultCustomModel> {
    return this.apiShippingAddressUserUserIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShippingAddressResponseListResultCustomModel>): ShippingAddressResponseListResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressUserUserIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressUserUserIdGet$Json$Response(params: ApiShippingAddressUserUserIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ShippingAddressResponseListResultCustomModel>> {
    return apiShippingAddressUserUserIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressUserUserIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressUserUserIdGet$Json(params: ApiShippingAddressUserUserIdGet$Json$Params, context?: HttpContext): Observable<ShippingAddressResponseListResultCustomModel> {
    return this.apiShippingAddressUserUserIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ShippingAddressResponseListResultCustomModel>): ShippingAddressResponseListResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiShippingAddressIdPut()` */
  static readonly ApiShippingAddressIdPutPath = '/api/ShippingAddress/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressIdPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiShippingAddressIdPut$Plain$Response(params: ApiShippingAddressIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
    return apiShippingAddressIdPut$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressIdPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiShippingAddressIdPut$Plain(params: ApiShippingAddressIdPut$Plain$Params, context?: HttpContext): Observable<ObjectResultCustomModel> {
    return this.apiShippingAddressIdPut$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectResultCustomModel>): ObjectResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressIdPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiShippingAddressIdPut$Json$Response(params: ApiShippingAddressIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
    return apiShippingAddressIdPut$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressIdPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiShippingAddressIdPut$Json(params: ApiShippingAddressIdPut$Json$Params, context?: HttpContext): Observable<ObjectResultCustomModel> {
    return this.apiShippingAddressIdPut$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectResultCustomModel>): ObjectResultCustomModel => r.body)
    );
  }

  /** Path part for operation `apiShippingAddressIdDelete()` */
  static readonly ApiShippingAddressIdDeletePath = '/api/ShippingAddress/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressIdDelete$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressIdDelete$Plain$Response(params: ApiShippingAddressIdDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
    return apiShippingAddressIdDelete$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressIdDelete$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressIdDelete$Plain(params: ApiShippingAddressIdDelete$Plain$Params, context?: HttpContext): Observable<ObjectResultCustomModel> {
    return this.apiShippingAddressIdDelete$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectResultCustomModel>): ObjectResultCustomModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiShippingAddressIdDelete$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressIdDelete$Json$Response(params: ApiShippingAddressIdDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ObjectResultCustomModel>> {
    return apiShippingAddressIdDelete$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiShippingAddressIdDelete$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiShippingAddressIdDelete$Json(params: ApiShippingAddressIdDelete$Json$Params, context?: HttpContext): Observable<ObjectResultCustomModel> {
    return this.apiShippingAddressIdDelete$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ObjectResultCustomModel>): ObjectResultCustomModel => r.body)
    );
  }

}
