/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUserCreatePost } from '../fn/user/api-user-create-post';
import { ApiUserCreatePost$Params } from '../fn/user/api-user-create-post';
import { apiUserDeleteIdDelete } from '../fn/user/api-user-delete-id-delete';
import { ApiUserDeleteIdDelete$Params } from '../fn/user/api-user-delete-id-delete';
import { apiUserGet } from '../fn/user/api-user-get';
import { ApiUserGet$Params } from '../fn/user/api-user-get';
import { apiUserIdGet } from '../fn/user/api-user-id-get';
import { ApiUserIdGet$Params } from '../fn/user/api-user-id-get';
import { apiUserSearchGet } from '../fn/user/api-user-search-get';
import { ApiUserSearchGet$Params } from '../fn/user/api-user-search-get';
import { apiUserUpdateIdPut } from '../fn/user/api-user-update-id-put';
import { ApiUserUpdateIdPut$Params } from '../fn/user/api-user-update-id-put';

@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUserGet()` */
  static readonly ApiUserGetPath = '/api/User';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Response(params?: ApiUserGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUserGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet(params?: ApiUserGet$Params, context?: HttpContext): Observable<void> {
    return this.apiUserGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUserIdGet()` */
  static readonly ApiUserIdGetPath = '/api/User/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Response(params: ApiUserIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUserIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet(params: ApiUserIdGet$Params, context?: HttpContext): Observable<void> {
    return this.apiUserIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUserCreatePost()` */
  static readonly ApiUserCreatePostPath = '/api/User/Create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserCreatePost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserCreatePost$Response(params?: ApiUserCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUserCreatePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserCreatePost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserCreatePost(params?: ApiUserCreatePost$Params, context?: HttpContext): Observable<void> {
    return this.apiUserCreatePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUserUpdateIdPut()` */
  static readonly ApiUserUpdateIdPutPath = '/api/User/Update/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserUpdateIdPut()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserUpdateIdPut$Response(params: ApiUserUpdateIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUserUpdateIdPut(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserUpdateIdPut$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserUpdateIdPut(params: ApiUserUpdateIdPut$Params, context?: HttpContext): Observable<void> {
    return this.apiUserUpdateIdPut$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUserDeleteIdDelete()` */
  static readonly ApiUserDeleteIdDeletePath = '/api/User/Delete/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserDeleteIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserDeleteIdDelete$Response(params: ApiUserDeleteIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUserDeleteIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserDeleteIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserDeleteIdDelete(params: ApiUserDeleteIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiUserDeleteIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUserSearchGet()` */
  static readonly ApiUserSearchGetPath = '/api/User/Search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserSearchGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserSearchGet$Response(params?: ApiUserSearchGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUserSearchGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserSearchGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserSearchGet(params?: ApiUserSearchGet$Params, context?: HttpContext): Observable<void> {
    return this.apiUserSearchGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
