/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderResponseResultCustomModel } from '../../models/order-response-result-custom-model';

export interface ApiOrderIdGet$Plain$Params {
  id: number;
}

export function apiOrderIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiOrderIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiOrderIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderResponseResultCustomModel>;
    })
  );
}

apiOrderIdGet$Plain.PATH = '/api/Order/{id}';
