/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderResponseListResultCustomModel } from '../../models/order-response-list-result-custom-model';

export interface ApiOrderUserUserIdGet$Plain$Params {
  userId: number;
}

export function apiOrderUserUserIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiOrderUserUserIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderResponseListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiOrderUserUserIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderResponseListResultCustomModel>;
    })
  );
}

apiOrderUserUserIdGet$Plain.PATH = '/api/Order/user/{userId}';
