/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StringResultCustomModel } from '../../models/string-result-custom-model';

export interface ApiOrderUpdateStatusIdPut$Plain$Params {
  id: number;
  status?: string;
}

export function apiOrderUpdateStatusIdPut$Plain(http: HttpClient, rootUrl: string, params: ApiOrderUpdateStatusIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiOrderUpdateStatusIdPut$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StringResultCustomModel>;
    })
  );
}

apiOrderUpdateStatusIdPut$Plain.PATH = '/api/Order/UpdateStatus/{id}';
