/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookResponseListResultCustomModel } from '../../models/book-response-list-result-custom-model';

export interface ApiBooksGet$Plain$Params {
}

export function apiBooksGet$Plain(http: HttpClient, rootUrl: string, params?: ApiBooksGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BookResponseListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiBooksGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookResponseListResultCustomModel>;
    })
  );
}

apiBooksGet$Plain.PATH = '/api/Books';
