/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookResponseResultCustomModel } from '../../models/book-response-result-custom-model';

export interface ApiBooksIdGet$Plain$Params {
  id: number;
}

export function apiBooksIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiBooksIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BookResponseResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiBooksIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BookResponseResultCustomModel>;
    })
  );
}

apiBooksIdGet$Plain.PATH = '/api/Books/{id}';
